apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-cloud-devops-capstone-deployment
  labels:
    app: web-app
spec:
  strategy:
    type: RollingUpdate
    maxUnavailable: 25%
    maxSurge: 25%
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: glanciano/udacity-cloud-devops-capstone:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-cloud-devops-capstone-deployment
  labels:
    app: web-app
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
